// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reminder struct {
	ID        int64
	ChatID    int64
	Text      string
	FireAt    pgtype.Timestamptz
	Sent      bool
	CreatedAt pgtype.Timestamptz
}
