// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (chat_id, text, fire_at)
VALUES ($1, $2, $3)
RETURNING id, chat_id, text, fire_at, sent, created_at
`

type CreateReminderParams struct {
	ChatID int64
	Text   string
	FireAt pgtype.Timestamptz
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder, arg.ChatID, arg.Text, arg.FireAt)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Text,
		&i.FireAt,
		&i.Sent,
		&i.CreatedAt,
	)
	return i, err
}

const getDueReminders = `-- name: GetDueReminders :many
SELECT id, chat_id, text, fire_at, sent, created_at
FROM reminders
WHERE sent = FALSE
    AND fire_at <= now()
ORDER BY fire_at
LIMIT 100
`

func (q *Queries) GetDueReminders(ctx context.Context) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, getDueReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Text,
			&i.FireAt,
			&i.Sent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPending = `-- name: ListPending :many
SELECT id, chat_id, text, fire_at, sent, created_at
FROM reminders
WHERE chat_id = $1
    AND sent = FALSE
ORDER BY fire_at
`

func (q *Queries) ListPending(ctx context.Context, chatID int64) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listPending, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Text,
			&i.FireAt,
			&i.Sent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSent = `-- name: MarkSent :exec
UPDATE reminders
SET sent = TRUE
WHERE id = $1
`

func (q *Queries) MarkSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSent, id)
	return err
}
